### ISSUE TITLE
对话接口"stream": False时异常

### ISSUE THREAD

**Issue by wgq-python** [LLM-Red-Team/hailuo-free-api#12]
_token存活live是true 但是对话失败 当"stream": False时 响应为{"code":-1000,"message":"Stream response error: undefined","data":null}
"stream": True时正常

**Comment by wgq-python** [comment]
之前正常，从昨天晚上开始异常

**Comment by Vinlic** [comment]
@wgq-python 0.0.16 已经跟进官方的更改
